### PR TITLE
FIDO2: set sign count = 0 on Silent GA

### PR DESCRIPTION
**Pull request by 0x0ptr**
Set the sign count to 0 on a Silent Assertion (SA). The sign count
cannot go backwards and thus a sign count of 0 is not a valid value.
Do this to ensure the returned assertion from an SA is not valid and cannot be
used for login.

### CODE REVIEW

**Comment by limpkin** [comment]
beautiful!

**Comment by My1** [comment]
sure that silent is disallowed on FIDO2 in general to be used or only for WebAuthn?

**Comment by limpkin** [comment]
i'm not sure to understand your question

**Comment by My1** [comment]
basically while FIDO2 is primarily used with WebAuthn, it is far from the only thing that uses WebAuthn.

OpenSSH, FIDO2Luks, Windows Login via AAD, pam-u2f (yes the name's outdated but hard to change I guess) and I honestly doubt that's all.

and at least pam-u2f and openssh have options to not require interaction for login (be it pin-only or completely silent is up to the config).

see e.g. https://wiki.archlinux.org/title/SSH_keys#FIDO/U2F

so what I am saying is that I think it's not quite as easy to assume that all UP=0 requests are just preflights checking out stuff (ideally it would be useful to compare counter behavior to other well established keys e.g. yubikeys)

also it might as well be possible that in the future silent Auth could be used as a keepalive for sessions (at least an Idea I had often enough)

**Pull request merged**
